# Generated by Django 3.2 on 2023-01-24 15:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(db_column='FirstName', max_length=16)),
                ('last_name', models.CharField(blank=True, db_column='LastName', max_length=16, null=True)),
                ('phone_no', models.CharField(db_column='PhoneNo', max_length=10, unique=True)),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=16, null=True, unique=True)),
                ('is_email_verified', models.BooleanField(db_column='IsEmailVerified', default=False)),
                ('is_prime_user', models.BooleanField(db_column='isPrime', default=False)),
                ('is_store_user', models.BooleanField(db_column='isStoreUser', default=False)),
                ('roles', models.JSONField(db_column='ROLES', default=[])),
                ('createdAt', models.DateTimeField(db_column='createdAt', default=datetime.datetime.now)),
                ('modifiedAt', models.DateTimeField(db_column='modifiedAt', default=datetime.datetime.now)),
                ('isDeleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('isActive', models.BooleanField(db_column='isActive', default=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(db_column='createdAt', default=datetime.datetime.now)),
                ('modifiedAt', models.DateTimeField(db_column='modifiedAt', default=datetime.datetime.now)),
                ('isDeleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('isActive', models.BooleanField(db_column='isActive', default=True)),
                ('primary_address', models.TextField(blank=True, db_column='primaryAddress', null=True)),
                ('secondary_address', models.TextField(blank=True, db_column='secondary_address', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(db_column='createdAt', default=datetime.datetime.now)),
                ('modifiedAt', models.DateTimeField(db_column='modifiedAt', default=datetime.datetime.now)),
                ('isDeleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('isActive', models.BooleanField(db_column='isActive', default=True)),
                ('role_name', models.CharField(db_column='roleName', max_length=16, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(db_column='createdAt', default=datetime.datetime.now)),
                ('modifiedAt', models.DateTimeField(db_column='modifiedAt', default=datetime.datetime.now)),
                ('isDeleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('isActive', models.BooleanField(db_column='isActive', default=True)),
                ('first_name', models.CharField(db_column='FirstName', max_length=16)),
                ('last_name', models.CharField(blank=True, db_column='LastName', max_length=16, null=True)),
                ('phone_no', models.CharField(db_column='PhoneNo', max_length=10, unique=True)),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=16, null=True, unique=True)),
                ('is_email_verified', models.BooleanField(db_column='IsEmailVerified', default=False)),
                ('is_prime_user', models.BooleanField(db_column='isPrime', default=False)),
                ('is_store_user', models.BooleanField(db_column='isStoreUser', default=False)),
                ('roles', models.JSONField(db_column='ROLES', default=[])),
                ('user_id', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, related_name='user_id_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreUserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(db_column='createdAt', default=datetime.datetime.now)),
                ('modifiedAt', models.DateTimeField(db_column='modifiedAt', default=datetime.datetime.now)),
                ('isDeleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('isActive', models.BooleanField(db_column='isActive', default=True)),
                ('user_id', models.CharField(db_column='StoreUserID', max_length=24, unique=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=256, null=True)),
                ('aadhar_no', models.CharField(blank=True, db_column='AadharNo', max_length=12, null=True)),
                ('pan_no', models.CharField(blank=True, db_column='PanNo', max_length=10, null=True)),
                ('dob', models.DateField(blank=True, db_column='DOB', null=True)),
                ('father_name', models.CharField(blank=True, db_column='FatherName', max_length=24, null=True)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('', '')], db_column='Gender', default='', max_length=1)),
                ('alternate_phone_no', models.CharField(blank=True, db_column='alternatePhone', max_length=10, null=True)),
                ('created_by', models.CharField(blank=True, db_column='createdBy', max_length=16, null=True)),
                ('employee_id', models.ForeignKey(db_column='EmployeeID', on_delete=django.db.models.deletion.CASCADE, related_name='store_employee_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
