# Generated by Django 2.2.4 on 2023-01-14 11:41

import datetime
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(db_column='StoreUserID', max_length=24, unique=True)),
                ('first_name', models.CharField(db_column='FirstName', max_length=16)),
                ('last_name', models.CharField(blank=True, db_column='LastName', max_length=16, null=True)),
                ('phone_no', models.CharField(db_column='PhoneNo', max_length=10, unique=True)),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=16, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=256, null=True)),
                ('aadhar_no', models.CharField(blank=True, db_column='AadharNo', max_length=12, null=True)),
                ('pan_no', models.CharField(blank=True, db_column='PanNo', max_length=10, null=True)),
                ('role', jsonfield.fields.JSONField(db_column='ROLE', default=dict, max_length=256)),
                ('dob', models.DateField(blank=True, db_column='DOB', null=True)),
                ('father_name', models.CharField(blank=True, db_column='FatherName', max_length=24, null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=1, null=True)),
                ('createdAt', models.DateTimeField(db_column='createdAt', default=datetime.datetime.now)),
                ('modifiedAt', models.DateTimeField(db_column='modifiedAt', default=datetime.datetime.now)),
                ('isDeleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('isActive', models.BooleanField(db_column='isActive', default=True)),
            ],
            options={
                'db_table': 'StoreUsers',
            },
        ),
    ]
